codefordc/us-congress-pizza-flag-tracker-frontend

src/components/Statuses.js

Statuses.js

---

src/components/AddOrder.js
src/components/Order.js
src/components/OrderForm.js
src/components/OrdersList.js
src/services/OrderService.js

closes #7 (re-merged to fix conflicts and deploy preview)

Rkaufman13 componentize

---

package-lock.json
package.json
src/components/OrderForm.js

set up combo boxes with React-Select for OrderForm.js

React select

---

src/components/OrderForm.js

remove duplicative /api/ from qrcode img

---

src/components/ScanOrder.js
src/components/Statuses.js

handled case where user reaches the final non-canceled status in an order's lifecycle:

collapsing sub-branch qr-update2-1 into qr-update2

---

src/components/ScanOrder.js

preliminary work to remote STATUSES.js dependency from the frontend at ScanOrder.js.  (move towards backend for single source of truth)

configuring statusServiceObject for QR Scan page

---

src/App.css
src/components/OrdersList.js
src/components/Sort/SortArrows.js
src/components/Sort/SortHook.js
src/components/TableHeader.js

This is a basic implementation that allows users to sort by any of the columns on the table (including 3 new ones that I added).
I'm marking this as a draft for a number of reasons...mostly, because it's ugly (help with UI wanted, thanks!), but also because I'm not sure how to handle the "order status" column. Right now it sorts in order of the status "sequence number", which is to say, orders earlier in the process are sorted higher than orders that have begun to move through the process. I think this is desired. But it's probably confusing, because we aren't exposing the sequence number to the user at any point.
This is done in vanilla React without any external libraries such as react-table , which SHOULD make it presentation-agnostic — it should work whether we continue to use a …

Sort table 

---

.huskyrc.json
src/components/AddOrder.js
src/components/EditOrder.js
src/components/OrdersList.js
src/components/ScanOrder.js
src/services/AuthService.js
src/services/OrderService.js

This PR incorporates the frontend changes needed to use the refresh token logic in (backend PR 98)[https://github.com/codefordc/us-congress-pizza-flag-tracker/pull/98]. The two PRs should be merged together.
Going forward, calls to the database (made through OrderDataService, etc) should be wrapped in AuthService.refreshTokenWrapperFunction so that if the user's authorization token is old but not expired, it will be refreshed.

Refreshtoken frontend

---

src/App.js
src/components/Profile.js

There was a `Profile.js` in the repo but it looked pretty old (still using class components, using old variable names, etc). I cleaned it up, made it accessible from the header, and have taken a stab at making the "authorizations" human-readable. However, I think a more long-term solution is to restructure the users table (sorry!) with a separate table for permissions. I'll create a separate issue on the backend to discuss.

make profile page appear and pretty!

---

src/components/ScanOrder.js

open to alternate message wording/phrasing

error handling for server error re:statuses

---

cypress/support/commands.js
tests.md

Makes running Cypress locally much easier, thanks Thad for `git add -f`

move config files to correct location

---

src/App.js
src/components/gauge.js
src/pages/addOrder.js
src/pages/addUser.js
src/pages/editOrder.js
src/pages/login.js
src/pages/ordersList.js
src/pages/profile.js
src/pages/scanOrder.js
src/style/gauge.module.css
src/style/orders.module.css

the addition of the status gauge from last wednesdays meeting

Status guage added and pages folder moved

---

src/pages/ordersList.js

there was concern a user would delete all the order by mistake
presumably developers can use run_setup.sh on the backend to reset the db for testing purposes as needed.

removed Remove All button by request

---

cypress/integration/flag_scan.js
cypress/support/commands.js

I'm feeling fairly confident that this works, but we won't be able to confirm it for 100% sure until we merge in @mertbagt 's PR to add the rest of the Congressional users.
Todo: add some "sad paths" and test the revert button

flag scan e2e test

---

src/pages/ordersList.js

removed redunant clear search button

---

src/App.js
src/components/header/privateHeader.js
src/components/passwordUpdate.js
src/components/protectedRoute/adminRoute.js
src/components/protectedRoute/permissions.js
src/components/protectedRoute/scanRoute.js
src/pages/ordersList.js
src/pages/scanOrder.js
src/service/userService.js
src/style/password.module.css

I fixed the scan redirect issue from the backlog and also hid the add order button from users who shouldnt have access

fixed scan redirection- DRAFT

---

package-lock.json
package.json
src/pages/scanOrder.js

done
Also:
Previously if the Order Status was complete, the UI buttons would not be rendered.
Now if the Order is manually advanced to complete by a user, the buttons are rendered so that the user can revert their change if needed.  If the Order was already at complete before a user takes any action, the buttons are not rendered as before.

gave Cong. Staffers ability to skip AOC_FLOWN status

---

cypress/integration/flag_scan.js
cypress/support/commands.js

Added the waits back in, and tweaked one of the commands to make it less brittle/susceptible to layout changes.

(re) add waits to cy tests

---

src/components/scanOrder/infoBottom.js
src/components/scanOrder/infoBottom/orderNotCancelled/orderNotCancelled.js
src/components/scanOrder/infoBottom/orderNotCancelled/orderNotDeclined/orderNotDeclined.js
src/components/scanOrder/infoBottom/orderNotCancelled/orderNotDeclined/orderNotReverted/orderNotReverted.js
src/components/scanOrder/infoBottom/orderOpen.js
src/pages/scanOrder.js

changed allowUpdate to be based on user.office_code instead of user.can_update_status_for

updated Scan view to align w/ security document, plus readability polish

---

src/components/header/header.js
src/components/orderForm.js
src/components/protectedRoute/scanRoute.js
src/pages/login.js
src/pages/ordersList.js
src/pages/scanOrder.js
src/style/orders.module.css

I added the constituent info where requested and updated scanning qr codes. Now when someone scans  a qr code without being logged in they are sent to login and then sent to the proper scan page.

fixes for tuesday

---

src/components/LogTable.js

I think the shape of the data returned may have changed 😳  we're getting the data more reliably now, I THINK, and I also wrapped everything in a useCallback because React was yelling at me.

third time's the charm for status table

---

src/components/gauge.js
src/pages/editOrder.js
src/pages/ordersList.js
src/service/statusService.js

Co-authored-by: Terence Stone
Co-authored-by: Rachel Kaufman <16939591+rkaufman13@users.noreply.github.com>
Co-authored-by: mertbagt <73559781+mertbagt@users.noreply.github.com>
Co-authored-by: Juan <pekingPow@users.noreply.github.com>
Please note this PR @aaronm759

add status label to each gauge on order list

---

src/components/header/header.js
src/components/header/privateHeader.js
src/pages/login.js
src/style/addUser.module.css
src/style/login.module.css
src/style/orderForm.module.css
src/style/orders.module.css
src/style/profile.module.css
src/style/scanOrder.module.css

header refreshes when logging in and logging out. I also simplified the layout to make it a bit more plain.

fixed header reload issue and simplified layout

---

src/pages/ordersList.js
src/style/orders.module.css

I think it works! Right now the states and offices are being generated from our hardcoded data; @Tmstone was working on fixing the routes/methods for this but IDK if it's ready yet. We can check in again tomorrow.
This tackles the first part of #83 . I think I said I would "maybe" get to the second part, but I did not--anyone want to jump in?

create 3 selects for searching and pass results to query string (#83)

---

src/App.js
src/components/demoLog.js
src/components/demoLogIn.js
src/components/userContext.js

issue #109: create URLs that demonstrators can use to quickly change login credentials for demo purposes
to activate append any base route with /demoLogin?q=[username]
where [username] is one of FED-ADMIN, FED-HOSS, FED-AOC, FED-MAIL, AL-01, etc

auto login URLS for issue 109

---

src/components/Search.js
src/pages/ordersList.js

Visiting `[app-url]?keyword=keyword` now populates the keyword in the search bar, as it should.
I'm struggling with getting React Select to listen to me, which is weird, as it's normally pretty cooperative.
Addresses the first half of #120; I'd love some advice on the second half!

keyword persistence works, but the dropdowns are gonna be tougher

---

src/pages/ordersList.js

reduced the number of rerenders generated by editOrderControl() function by using useEffect hook

Fewer order list renders

---

src/components/addView.js
src/components/demoLogIn.js
src/components/loginSubComponent.js
src/components/ordersView.js
src/components/userContext.js

removed meaningless parameters from setUserDisplay
setUserDisplay uses Context so that demoLogin and loginSubComponent can force Header to update and rerender

Login routing

---

src/components/demoLogIn.js
src/pages/ordersList.js

welcome component, subcomponents to OrderList.js so that:
welcome page displays on 'base route' "/" when the user isn't logged in.

Welcome page container revised

---

src/components/ordersView.js
src/components/scanOrder/scanView.js

hey, small PR as promised before tomorrow. The links are quick and dirty but they work!

remove buttons from order list page, move to scan page

---

cypress/integration/basic_tests.js
src/components/editView.js
src/components/orderForm.js
src/components/scanOrder/scanView.js

basic tests fixed

---

cypress/integration/basic_tests.js
cypress/integration/state_admin_tests.js
cypress/support/commands.js
src/components/ordersView.js

hey all--got some fixes to flaky tests here plus a few new ones. still haven't gotten through Merritt's excellent list so there is more to do.
My linter is failing on line 47 of `src/components/ordersView.js` even with the eslint-disable comment. I'll look into it at some point.

MOAR cypress tests
